name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    continue-on-error: "${{ github.ref == 'refs/heads/master' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up clang-format
        uses: egor-tensin/setup-clang@v2
        with:
          # To use the latest clang-format features:
          version: 22
      - name: Run clang-format
        uses: egor-tensin/clang-format@v1
        with:
          version: 22

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, windows-2025]
        platform: [x64, x86]
        configuration: [Debug, RelWithDebInfo]
        include:
          - boost-version: 1.81.0
          # MinGW builds are done on Linux, since it's more up-to-date there,
          # and it's much faster.
          - {os: ubuntu-latest, toolset: mingw}
          - {os: windows-2022, toolset: vs2022}
          # Boost supports VS 2026 starting with version 1.91, I think?
          - {os: windows-2025, toolset: vs2026, boost-version: 1.91.0}

    runs-on: '${{ matrix.os }}'
    name: 'Build: ${{ matrix.os }} / ${{ matrix.platform }} / ${{ matrix.configuration }}'
    env:
      TOOLSET: '${{ matrix.toolset }}'
      PLATFORM: '${{ matrix.platform }}'
      CONFIGURATION: '${{ matrix.configuration }}'
      BOOST_VERSION: '${{ matrix.boost-version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Cache Boost
        uses: actions/cache@v6
        with:
          path: './build/boost_*.tar.gz'
          key: 'boost_${{ env.BOOST_VERSION }}'
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: '${{ matrix.platform }}'
        if: matrix.toolset == 'mingw'
      - name: Build Boost
        run: make deps
      - name: Build
        run: make install
      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: 'winapi-debug-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.configuration }}'
          path: './build/install/'
          if-no-files-found: error
      - name: Test
        run: make test
        if: runner.os == 'Windows'
