name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Run clang-format
        uses: egor-tensin/clang-format@v1

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, windows-2025]
        platform: [x64, x86]
        configuration: [Debug, RelWithDebInfo]
        include:
          - boost-version: 1.81.0
          # MinGW builds are done on Linux, since it's more up-to-date there,
          # and it's much faster.
          - {os: ubuntu-latest, toolset: mingw}
          - {os: windows-2022, toolset: vs2022}
          # At the moment, the 2025 image still has VS 2022.
          - {os: windows-2025, toolset: vs2022}

    runs-on: '${{ matrix.os }}'
    name: 'Build: ${{ matrix.os }} / ${{ matrix.platform }} / ${{ matrix.configuration }}'
    defaults:
      run:
        shell: pwsh
    env:
      TOOLSET: '${{ matrix.toolset }}'
      PLATFORM: '${{ matrix.platform }}'
      CONFIGURATION: '${{ matrix.configuration }}'
      BOOST_VERSION: '${{ matrix.boost-version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Cache Boost
        uses: actions/cache@v5
        with:
          path: './build/boost_*.tar.gz'
          key: 'boost_${{ env.BOOST_VERSION }}'
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: '${{ matrix.platform }}'
        if: matrix.toolset == 'mingw'
      - name: Build Boost
        run: make deps
      - name: Build
        run: make install
      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          name: 'winapi-debug-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.configuration }}'
          path: './build/install/'
          if-no-files-found: error
      - name: Test
        run: make test
        if: runner.os == 'Windows'
